<div class="k2_calendar_form">    
    <?php KumbiaPHP\View\View::content(true) ?>
    <?php echo $form->open() ?>
    <div class="k2_calendar_errors ui-state-error ui-corner-all"></div>
    <dl>
        <?php foreach ($form->getFields() as $field): ?>
            <dd><label><?php echo $field['label'] ?></label></dd>
            <dt><?php echo $field ?></dt>
        <?php endforeach; ?>
    </dl>
    <?php echo $form->close() ?>
</div>
